build_image:
  stage: build
  image: docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

mirror_to_github:
  stage: deploy
  image: alpine
  script:
    - apk --no-cache add git openssh
    - mkdir -p /root/.ssh
    - chmod 700 /root/.ssh
    - echo "$TOGITHUB" > /root/.ssh/id_rsa
    - git push -u git@github.com:hhucn/hardprog-docker.git master
